# Autogenerated wrapper script for f4ncgb_jll for x86_64-linux-musl-cxx11
export f4ncgb, libf4ncgb

using GMP_jll
using MPFR_jll
using FLINT_jll
using boost_jll
JLLWrappers.@generate_wrapper_header("f4ncgb")
JLLWrappers.@declare_library_product(libf4ncgb, "libf4ncgb.so")
JLLWrappers.@declare_executable_product(f4ncgb)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, MPFR_jll, FLINT_jll, boost_jll)
    JLLWrappers.@init_library_product(
        libf4ncgb,
        "lib/libf4ncgb.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        f4ncgb,
        "bin/f4ncgb",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
